USE [QuizDB]
GO

INSERT INTO [dbo].[Learning]
([Subtitle],[TextKey],[QuizId],[ChangeUser],[ChangeDate],[CreateUser],[CreateDate])
VALUES
('Definition','E-Contracting umfasst den kompletten elektronischen Vertragsprozess und relevante Dokumente der Vertragshandlung (z.B. Protokolle). Es ist kein physischer oder persönlicher Kontakt nötig. Sobald der Vertragsprozess beendet ist, sind die Parteien rechtsgültig an den Vertrag gebunden. Sämtliche Phasen der Geschäftstransaktion sind im E-Contracting enthalten.',1,CURRENT_USER,CURRENT_TIMESTAMP,CURRENT_USER,CURRENT_TIMESTAMP),
('Konzept','Ein elektronischer Vertrag weist andere Merkmale auf als Papierverträge. Während ein papierbasiertes Vertragsdokument eine statische Ansicht der Rechte und Pflichten der Vertragsparteien darstellt, könnte ein elektronischer Vertrag diese Rechte und Pflichten tatsächlich während der Laufzeit der Vereinbarung überwachen. E-Verträge werden nicht nur als rechtsverbindliche Vereinbarung zwischen Käufer und Verkäufer verwendet, sondern können auch über verschiedene organisatorische Geschäftsprozesse hinweg verwendet werden. E-Contracting umfasst zwei Phasen: Vertragserstellung und Vertragserfüllung (Vertragserfüllung, Compliance).',1,CURRENT_USER,CURRENT_TIMESTAMP,CURRENT_USER,CURRENT_TIMESTAMP),
('Gesetz','Gesetzliche Regelungen, wie die europäische Richtlinie für elektronische Signaturen und nationale E-Commerce-Verordnungen, haben einen Rahmen für den Einsatz elektronischer Verträge im Geschäftsverkehr geschaffen.',1,CURRENT_USER,CURRENT_TIMESTAMP,CURRENT_USER,CURRENT_TIMESTAMP),
('Zweck','Der Zweck der Nutzung eines E-Vertrags ist zweierlei. Erstens bietet der Vertrag allen Vertragspartnern eine Garantie gemäß den Klauseln des unterzeichneten Vertrages und den einschlägigen Gesetzen. Zweitens bauen Vertragspartner über einen E-Vertrag eine Geschäftsbeziehung auf. Für die Begründung eines E-Vertrags gibt es drei kritische Aspekte (Vertragsinhalt vereinbaren die Parteien einvernehmlich). Zuerst muss das Thema genau definiert werden. Zweitens wird die Rechtsgültigkeit formuliert. Drittens müssen der Preis und die Bedingungen jeder Klausel in Bezug auf die Qualität der Leistungen und der Dienstleistungen sowie in Bezug auf die rechtlichen Bedingungen ausgehandelt werden.',1,CURRENT_USER,CURRENT_TIMESTAMP,CURRENT_USER,CURRENT_TIMESTAMP),
('Durchführung','Beim E-Contracting wird ein elektronischer Verhandlungsprozess mithilfe von Standards durchgeführt, die zur Erstellung eines rechtsgültigen Dokuments mit digitaler Signatur dienen. Es sind verschiedene Aktivitäten notwendig: generische Dienste zur Verhandlung, Validierung, Unterzeichnung, Abwicklung, Archivierung und Schlichtung. Dazu werden asymmetrische Verschlüsselungsverfahren und digitale Signaturen sowie Zertifikate benötigt.',1,CURRENT_USER,CURRENT_TIMESTAMP,CURRENT_USER,CURRENT_TIMESTAMP),
('Vorteile',', E-Contracting kann Vertragspartner in elektronischen Umgebungen schützen, Vertragslaufzeiten verkürzen und Prozesskosten senken. Es kann auch neue Möglichkeiten für das Vertragsmanagement, die Wiederverwendung von Vertragsinhalten und die Vertragsüberwachung bieten. Zudem können Fehler vermieden werden, Vorlagen genutzt und maschinenverarbeitbare Daten.',1,CURRENT_USER,CURRENT_TIMESTAMP,CURRENT_USER,CURRENT_TIMESTAMP),
('Erstellung','Je nachdem, ob während der Gründungsphase Netzwerke genutzt werden, können E-Verträge online oder offline erstellt werden. Die Zusammenarbeit kann asynchron (z.B. per E-Mail) oder synchron (z.B. Online-Plattform) erfolgen. Der Prozess kann auf einer gemeinsamen Plattform (E-Signatur) abgeschlossen werden.',1,CURRENT_USER,CURRENT_TIMESTAMP,CURRENT_USER,CURRENT_TIMESTAMP)
GO


